Transform: AWS::Serverless-2016-10-31
Parameters:
  AppId:
    Type: String

Resources:
  helloFromLambdaFunctionF4:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-f4/
      Handler: silly.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 60
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Events:
        helloFromLambdaF4FunctionApi:
          Type: Api
          Properties:
            # restapi_TOKEN=!Ref BasicAWSApiGateway
            RestApiId: restapi_TOKEN
            Path: /lambda-f4
            Method: GET
